[package]
name = "chatroom-client"
version = "0.1.0"
edition = "2021"

[dependencies]
druid = "0.8.3"
async-std = {version = "1.13.0", features = ["attributes"]}
futures = "0.3.31"
chatroom-net = {path = "../net"}