[package]
name = "chatroom-server"
version = "0.1.0"
edition = "2021"

[dependencies]
chatroom-net = {path = "../net"}
async-std = {version = "1.13.0", features = ["attributes"]}
futures = "0.3.31"
serde_json = "1.0.132"
