[package]
name = "chatroom-net"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
async-std = {version = "1.13.0", features = ["attributes"]}
futures = "0.3.31"
druid = "0.8.3"
sha2 = "0.10.8"
hex = "0.4.3"
